### ISSUE TITLE
Incompatible with terrain tools

### ISSUE THREAD

**Issue by AetherealGlow** [shudnal/BuildPiecesCustomized#1]
This mod seems to have issues with Searica's Advanced Terrain Modifiers.  When using terrain tools that have an adjustable dashed white circle (that can be expanded with the mouse wheel) the circle is "stuck" and won't move, but only when this mod is enabled.

**Comment by shudnal** [comment]
I had a look and it works just fine with only that two mods installed. Circle radius is adjusting and everything looks like working as intended.
If you provide steps to reproduce that I will have another look but for now I don't see an issue.

**Comment by AetherealGlow** [comment]
Sorry, my mistake.  The issue is with the Infinity Tools plugin for Infinity Hammer.
