### ISSUE TITLE
Incompatible with Infinity Tools

### ISSUE THREAD

**Issue by AetherealGlow** [shudnal/BuildPiecesCustomized#2]
This mod causes issues with the Infinity Hammer plugin, Infinity Tools.  Specifically it can cause issues with the adjustable terrain tool where the circle will no longer move.  There also seems to be an issue with the health/invulnerability of built pieces, even after this mod has been uninstalled.  I think the mod may do something to the build pieces that makes the Infinity Hammer no longer recognize them as belonging to the player, and then the player can't repair them when they decay.  Jere Kuusela, the author of Infinity Hammer says the code in BPC is incompatible with his code.  But I only have the issues with the Infinity Tools plugin, not Infinity Hammer without the Infinity Tools.  Idk what you want to do about it, but it might be good to put something in the description about this compatibility issue, as the effects can really mess up player buildings.

![wholehouse](https://github.com/shudnal/BuildPiecesCustomized/assets/81339406/712fc484-bb90-4ce9-a705-73f4a72b6c81)

**Comment by shudnal** [comment]
Thanks, I'll add strict incompatibility with Infinity Hammer as it's indeed incompatible since the similar nature of changes.

**Comment by shudnal** [comment]
Pls check 1.0.4. It should be compatible now.
